# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-17 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=200)),
                ('abv', models.FloatField(max_length=50)),
                ('plato', models.FloatField(max_length=50)),
                ('expired_date', models.DateTimeField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery_name', models.CharField(max_length=200)),
                ('hometown', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerlist.Brewery'),
        ),
    ]
