# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-17 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='is_in_library',
            field=models.BooleanField(default=False),
        ),
    ]
