# Generated by Django 2.0.13 on 2020-03-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerlist', '0002_beer_is_in_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='album_logo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
