# Generated by Django 2.0.13 on 2020-03-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beerlist', '0003_brewery_album_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewery',
            old_name='album_logo',
            new_name='brewery_logo',
        ),
    ]
